USE db_boutique;

/* testing customers */
INSERT INTO `customer` (`gender`, `firstname`, `lastname`, `email`, `password`, `auth_level`, `birthdate`, `main_phone_number`, `secondary_phone_number`, `credit_card_holder`, `credit_card_number`, `credit_card_expiration`, `del_address_id`, `bil_address_id`) VALUES ('M', 'Charles', 'Admin', 'admin@admin.admin', '21232f297a57a5a743894a0e4a801fc3', '1', NULL, '0606060606', NULL, NULL, NULL, NULL, NULL, NULL), ('F', 'Michelle', 'User', 'user@user.user', 'ee11cbb19052e40b07aac0ca060c23ee', '0', NULL, '0606060606', NULL, NULL, NULL, NULL, NULL, NULL);

/*brands*/
INSERT INTO `brand` (`name`) VALUES ('Jordan'), ('Adidas'), ('Nike'), ('Reebok'), ('New Balance');

/*categories*/
INSERT INTO `category` (`name`, `description`) VALUES ('Femme', NULL), ('Homme', NULL);

/*products*/
INSERT INTO `product` (`ref`, `name`, `description`, `price`, `picture_name`, `is_available`, `is_on_promo`, `reduction_percent`, `promo_price`, `is_in_selection`, `brand_id`, `category_id`) VALUES ('B42204', 'Adidas ZX 500 RM - Grey Four/White', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe accusamus non consequatur natus, adipisci commodi, odit. Recusandae, corrupti, hic. Molestiae magni, itaque natus eum fugiat beatae impedit, corporis quam ipsam.', '139.00', 'ad_zx500rm_gfw.png', '1', NULL, NULL, NULL, NULL, '2', '2'), ('6163715014', 'New Balance WL574 ESV - Daybreak', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A dicta inventore eos repellendus voluptatum hic voluptas nam totam at, culpa excepturi tempore, veritatis illum perferendis non quibusdam voluptate ratione unde.', '89.00', 'nb_wl574esv_d.png', '1', '1', '40', '54.40', NULL, '5', '1'), ('AJ8207601', 'Jordan Flyknit Elevation 23 - University Red/Back', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae autem voluptas nihil nobis deserunt aliquam totam, consequuntur vitae eaque dignissimos esse consequatur quas nam explicabo rem veritatis delectus quos voluptatum.', '159.00', 'jo_fe23_rb.png', '1', NULL, NULL, NULL, '1', '1', '2'), ('AO1069106', 'Nike W Outburst - White/Team Orange', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit amet consequuntur magni perspiciatis, dignissimos nam expedita suscipit aliquid ea praesentium necessitatibus facilis hic explicabo aspernatur, ullam dolorum tempore cupiditate aliquam.', '89.00', 'nk_woutburst.png', '1', NULL, NULL, NULL, '1', '3', '1'), ('CN0135', 'Reebok Instapump Fury OG Ultraknit - Black/Blue/Red', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed enim amet maxime debitis nam, dolorum corporis architecto quae totam, atque perspiciatis! Quam numquam reprehenderit, vero quibusdam maiores quidem, pariatur facere!', '229.00', 're_ifogu_blablur.png', '1', '1', '50', '114.50', '1', '4', '2');

/*sizes*/
INSERT INTO `size` (`size`) VALUES ('34'), ('34 ½'), ('35'), ('35 ½'), ('36'), ('36 ½'), ('37'), ('37 ½'), ('38'), ('38 ½'), ('39'), ('39 ½'), ('40'), ('40 ½'), ('41'), ('41 ½'), ('42'), ('42 ½'), ('43'), ('43 ½'), ('44'), ('44 ½'), ('45'), ('45 ½'), ('46'), ('46 ½'), ('47'), ('47 ½');

/*product sizes*/
INSERT INTO `product_size` (`stock`, `product_id`, `size_id`) VALUES ('100', '1', '9'), ('100', '1', '10'), ('70', '1', '11'), ('50', '1', '12'), ('40', '1', '13'), ('120', '2', '4'), ('130', '2', '5'), ('150', '2', '6'), ('70', '3', '8'), ('80', '3', '9'), ('90', '3', '10'), ('100', '3', '11'), ('90', '3', '12'), ('80', '3', '13'), ('70', '3', '14'), ('80', '4', '17'), ('100', '4', '18'), ('100', '4', '19'), ('100', '4', '20'), ('90', '4', '21'), ('80', '4', '22'), ('70', '5', '7'), ('80', '5', '8'), ('90', '5', '9'), ('100', '5', '10'), ('90', '5', '11'), ('80', '5', '12')